### PR TITLE
Entity gantt

### PR DESCRIPTION
**Pull request by mishinaolia**
Make sure that all fields of the Gantt chart after filling contain accurate results and that all fields are correctly saved. The chart should display.

### CODE REVIEW

**Review by GalinaRuban — CHANGES_REQUESTED** [review]
Too many extra lines at the end

**Review by mishinaolia — COMMENTED** [review]
I do not see a sleep method in my test.

**Review by Stan575 — APPROVED** [review]

**Comment by oooleks** [comment]
There is no need to create Actions object multiple times in your test (like: `Actions builder = new Actions(driver);`).
Do it only one time at the beginning and use the variable when needed.

**Comment by mishinaolia** [comment]
Ok, thank you . I will know .

**Comment by oooleks** [comment]
Closing the PR as committed Gantt test is obsolete

**Pull request closed without merging**
