### PR TITLE
Lisa j test

### PR DESCRIPTION
**Pull request by Kotova9478**
Created pull request

### CODE REVIEW

**Review by Stan575 — CHANGES_REQUESTED** [review]
Please delete unnecessary empty lines, and add at least one assertion at the end of test, cuz as is, everything after line 28 has no effect.

**Comment by pinchukstsiapan** [comment]
Krasota

**Review by ErikHP — APPROVED** [review]

**Comment by ErikHP** [comment]
Amazing test!

**Review by Stan575 — APPROVED** [review]
Great job!
Only one small suggestion, to use empty lines as logical dividers, in some cases like lines 92 and 94 look connected in the flow so empty line between them can be deleted

**Pull request merged**
