### PR TITLE
test - placeholder record with placeholder values

### PR DESCRIPTION
**Pull request by Vadym11**
test placeholder record with placeholder values (added to the existing class)

### CODE REVIEW

**Review by Stan575 — DISMISSED** [review]
Delete commented out code

**Comment by Vadym11** [comment]
> Delete commented out code

I'm still fixing the code, it works locally, but Travis keeps giving me errors. As soon as I'm done fixing, I will delete all commented code

**Review by halamelnyk — APPROVED** [review]

**Comment by Stan575** [comment]
@Vadym11 looks good, I assume test still being in progress cuz don't see any assertions at this time, ping me when you finish

**Comment by Vadym11** [comment]
> @Vadym11 looks good, I assume test still being in progress cuz don't see any assertions at this time, ping me when you finish

actually, it's finished and merged, Sergey helped me out to fix a problem regarding date and time fields, assertions are on lines 104-107

**Comment by Stan575** [comment]
> > @Vadym11 looks good, I assume test still being in progress cuz don't see any assertions at this time, ping me when you finish
> 
> actually, it's finished and merged, Sergey helped me out to fix a problem regarding date and time fields, assertions are on lines 104-107

Validations (assertions) start with Assert.assert --something here--, if it's fine with Sergey there's no problem with me

**Comment by Vadym11** [comment]
> > > @Vadym11 looks good, I assume test still being in progress cuz don't see any assertions at this time, ping me when you finish
> > 
> > 
> > actually, it's finished and merged, Sergey helped me out to fix a problem regarding date and time fields, assertions are on lines 104-107
> 
> Validations (assertions) start with Assert.assert --something here--, if it's fine with Sergey there's no problem with me

yes, you are right, I had assertions in the first version of my code, but Sergey said that at this point if we can just find newly created records in the records list, that's would be enough for now. Anyway I appreciate you looking over my test

**Pull request merged**
