### PR TITLE
Entity import edit pk

### PR DESCRIPTION
**Pull request by PeterKuzyk**
refactor importEditSelectForEmbeded  
add importEditSelectForEmbededCustom()

https://trello.com/c/vavTMRhC/351-entity-import-edit

bug in - importEditFilteredImport3()
https://trello.com/c/E6E4Rv6p/58-entity-import-edit-filtered-import3-does-not-transfer-data-to-import-page

Ignore
https://trello.com/c/9BcSFWG2/434-entityexporttest

https://trello.com/c/DEXBAucp/436-entityarithmeticintest

https://trello.com/c/aQZfY20L/438-entityfields1test

### CODE REVIEW

**Review by sergeonevdah — APPROVED** [review]

**Comment by Stan575** [comment]
@PeterKuzyk Is gradle stuff expected to be in this PR?

**Review by SergeiDemyanenko — CHANGES_REQUESTED** [review]
А зачем нужны тут файлы bin, lock и т.д.?

**Comment by SergeiDemyanenko** [comment]
Все еще есть лишние файлы в этом PR

**Review by PeterKuzyk — COMMENTED** [review]
Foles is deleted from push

**Review by ArinaJur — APPROVED** [review]

**Review by Stan575 — CHANGES_REQUESTED** [review]
Remove all gradle related stuff from PR

**Review by sergeonevdah — APPROVED** [review]

**Comment by sergeonevdah** [comment]
> Remove all gradle related stuff from PR

**Comment by PeterKuzyk** [comment]
> Remove all gradle related stuff from PR

Hi file Delited.

**Comment by oooleks** [comment]
- Use standard waiter (getWebDriverWait()) instead:
`
 WebDriverWait wait = new WebDriverWait(driver, 3);
        WebElement importButton = driver.findElement(By.xpath("//i[contains(text(), 'create_new_folder')]"));
        wait.until(ExpectedConditions.elementToBeClickable(importButton));
`

- Better to use String.format insted of concatenation:
`By.xpath("//div[contains(text(),'" + STRING + "')]")`

**Pull request merged**
